version: '3'

services:
  ansible-controller:
    container_name: ansible-controller
    image: choisunguk/ansible:3.11.7-bookworm-controller
    networks:
      - ansible-network
    command: tail -f /dev/null

  ansible-node0:
    container_name: ansible-node1
    image: choisunguk/ansible:3.11.7-bookworm-managed-node
    networks:
      - ansible-network

  ansible-node1:
    container_name: ansible-node2
    image: choisunguk/ansible:3.11.7-bookworm-managed-node
    networks:
      - ansible-network

networks:
  ansible-network:
    driver: bridge
